import { ArcaneCollection } from '@warfarmer/types';

export const arcaneCollection: Record<ArcaneCollection, string[]> = {
  Duviri: [
    'Arcane Intention',
    'Magus Aggress',
    'Arcane Power Ramp',
    'Primary Blight',
    'Primary Exhilarate',
    'Primary Obstruct',
    'Shotgun Vendetta',
    'Akimbo Slip Shot',
    'Secondary Outburst',
    'Arcane Reaper',
    'Longbow Sharpshot',
    'Secondary Shiver',
  ],
  Eidolon: [
    'Arcane Consequence',
    'Arcane Ice',
    'Arcane Momentum',
    'Arcane Nullifier',
    'Arcane Tempo',
    'Arcane Warmth',
    'Arcane Acceleration',
    'Arcane Agility',
    'Arcane Awakening',
    'Arcane Deflection',
    'Arcane Eruption',
    'Arcane Guardian',
    'Arcane Healing',
    'Arcane Phantasm',
    'Arcane Resistance',
    'Arcane Strike',
    'Arcane Trickery',
    'Arcane Velocity',
    'Arcane Victory',
    'Arcane Aegis',
    'Arcane Arachne',
    'Arcane Avenger',
    'Arcane Fury',
    'Arcane Precision',
    'Arcane Pulse',
    'Arcane Rage',
    'Arcane Ultimatum',
    'Arcane Barrier',
    'Arcane Energize',
    'Arcane Grace',
  ],
  Holdfasts: [
    'Arcane Blessing',
    'Arcane Rise',
    'Molt Augmented',
    'Molt Efficiency',
    'Molt Reconstruct',
    'Molt Vigor',
    'Fractalized Reset',
    'Cascadia Accuracy',
    'Cascadia Empowered',
    'Cascadia Flare',
    'Cascadia Overcharge',
    'Conjunction Voltage',
    'Emergence Dissipate',
    'Emergence Renewed',
    'Emergence Savior',
    'Eternal Eradicate',
    'Eternal Logistics',
    'Eternal Onslaught',
    'Primary Frostbite',
  ],
  Necralisk: [
    'Arcane Steadfast',
    'Arcane Double Back',
    'Theorem Contagion',
    'Theorem Infection',
    'Theorem Demulcent',
    'Primary Plated Round',
    'Secondary Encumber',
    'Secondary Kinship',
    'Residual Boils',
    'Residual Malodor',
    'Residual Shock',
    'Residual Viremia',
  ],
  Ostron: [
    'Magus Husk',
    'Magus Vigor',
    'Virtuos Null',
    'Virtuos Tempo',
    'Exodia Triumph',
    'Exodia Valor',
    'Magus Cadence',
    'Magus Cloud',
    'Magus Replenish',
    'Virtuos Fury',
    'Virtuos Strike',
    'Exodia Brave',
    'Exodia Force',
    'Exodia Hunt',
    'Exodia Might',
    'Magus Elevate',
    'Magus Nourish',
    'Virtuos Ghost',
    'Virtuos Shadow',
  ],
  Solaris: [
    'Magus Accelerant',
    'Magus Anomaly',
    'Magus Drive',
    'Magus Firewall',
    'Magus Overload',
    'Virtuos Spike',
    'Virtuos Surge',
    'Magus Glitch',
    'Magus Repair',
    'Virtuos Forge',
    'Virtuos Trojan',
    'Pax Bolt',
    'Pax Charge',
    'Pax Seeker',
    'Pax Soar',
    'Magus Destruct',
    'Magus Lockdown',
    'Magus Melt',
    'Magus Revert',
  ],
  Steel: [
    'Arcane Blade Charger',
    'Arcane Bodyguard',
    'Arcane Pistoleer',
    'Arcane Primary Charger',
    'Arcane Tanker',
    'Primary Deadhead',
    'Primary Dexterity',
    'Primary Merciless',
    'Secondary Deadhead',
    'Secondary Dexterity',
    'Secondary Merciless',
  ],
};
