name: Deploy to Docker Swarm

on:
  push:
    branches:
      - main
    paths:
      - 'apps/warfarmer-api/**'
      - 'libs/**'
      - 'prisma/**'
      - 'nx.json'
      - 'package.json'
      - 'tsconfig.base.json'
      - 'tsconfig.json'
      - 'workspace.json'
      - '.github/workflows/wf-api-deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build prisma dependency
        run: npx nx run api-prisma-schema:generate-types

      - name: Lint
        run: npx nx run warfarmer-api:lint

      - name: Test
        run: npx nx run warfarmer-api:test

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./apps/warfarmer-api/Dockerfile
          push: true
          tags: |
            poowaa/warfarmer-api:latest
            poowaa/warfarmer-api:${{ github.sha }}

      - name: Run Prisma migrations
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Deploy to Portainer via WebHook
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.PORTAINER_WEBHOOK_URL }}
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json"}'
